In [1]:
import numpy as np
import random

In [2]:
# Creating boards dictionary
board_dic = dict()

# Creating the chess boards
for i in range(0,4):
    board_dic[i] = np.zeros((8,8))


In [3]:
# Defining function for placing queen at random position on each board
def placeQueens(board):
    for i in range(0,8):
        row = random.randint(0,7)
        col = i
        board[row][col] = 1

# Defining function for creating list represntation of each board
def createList(board):
    index = list()
    for col in range(0,8):
        for row in range(0,8):
            if board[row][col] == 1:
                index.append(row)
                break
    return index


In [4]:
# Placing queens at random numbers on each board
for i in range(0,4):
    placeQueens(board_dic[i])

# Creating list representation of each board
list_dic = dict()

for i in range(0,4):
    list_dic[i] = createList(board_dic[i])

In [5]:
# Horizontal check

def checkHorizontal(board,row,col):
    #checking left side
    cl = col-1
    for i in range(0 , 8):
        if cl < 0:
            break
        elif board[row][cl] == 1:
            return False
        else:
            cl -=1
        
    #checking right side
    cl = col + 1
    for i in range(0 , 8):
        if cl > 7:
            break
        elif board[row][cl] == 1:
            return False
        else:
            cl +=1
    return True
                
def checkVertical(board,row,col):
    #checking top
    ro = row -1
    for i in range(0, 8):
        if ro < 0:
            break
        elif board[ro][col] == 1:
            return False
        else:
            ro -=1
        
    #checking bottom
    ro = row + 1
    for i in range(0, 8):
        if ro > 7:
            break
        elif board[ro][col] == 1:
            return False
        else:
            ro +=1
    return True
            

In [6]:
# Diagonal check

def checkDiagonal(board,row,col):
    #checking upper left diagonal
    cl = col - 1
    ro = row - 1
    for i in range(8):
        if ro < 0 or cl < 0:
            break
        elif board[ro][cl] == 1:
            return False
        else:
            cl = cl - 1
            ro = ro - 1
    
    #checking upper right diagonal
    cl = col + 1
    ro = row - 1
    for i in range(8):
        if ro < 0 or cl > 7:
            break
        elif board[ro][cl] == 1:
            return False
        else:
            cl += 1
            ro -= 1
    
    #checking lower left diagonal
    cl = col - 1
    ro = row + 1
    for i in range(8):
        if ro > 7 or cl < 0:
            break
        elif board[ro][cl] == 1:
            return False
        else:
            cl -= 1
            ro += 1
            
    #checking lower right diagonal
    cl = col + 1
    ro = row + 1
    for i in range(8):
        if ro > 7 or cl > 7:
            break
        elif board[ro][cl] == 1:
            return False
        else:
            cl += 1
            ro += 1
    return True

    

In [10]:
# creating fitness function
# and checkVertical(board,row,col) and checkDiagonal(board,row,col)
def checkFitness(board):
    count = 0
    for col in range(0,8):
        for row in range(0,8):
            if board[row][col] == 1:
                if(checkHorizontal(board, row, col) and checkVertical(board,row,col) and checkDiagonal(board,row,col) ):
                    count +=1
    return count
                   
# Defining function for getting worst 2 boards index

def getWorst2(best_2):
    worst_2 = [0,0]
    count = 0
    for i in range(0,4):
        if i != best_2[0] and i != best_2[1] :
            worst_2[count] = i
            count +=1
    return worst_2

# Defining function for getting best 2 boards index

def getBest2(values):
    return sorted(range(len(values)), key=lambda i: values[i])[-2:]

# Functions for generating off springs
def getFirstOffSpring(list_dic, best_2):
    offSpring = [0,0,0,0,0,0,0,0]
    for i in range(0,4):
        offSpring[i] = list_dic[best_2[0]][i]
    for i in range(4,8):
        offSpring[i] = list_dic[best_2[1]][i]
    return offSpring
def getSecondOffSpring(list_dic, best_2):
    offSpring = [0,0,0,0,0,0,0,0]
    for i in range(0,4):
        offSpring[i] = list_dic[best_2[1]][i]
    for i in range(4,8):
        offSpring[i] = list_dic[best_2[0]][i]
    return offSpring

# Defining function for performing mutation

def mutate(offSpring):
    col = random.randint(0,7)
    val = random.randint(0,7)
    offSpring[col] = val

# Defining function for updating the board with offsprings

def updateBoard(list_dic, worst_2):
    board = np.zeros((8,8))
    for i in range(0,8):
        row = list_dic[worst_2][i]
        board[row][i] = 1
    return board
    

In [9]:
values = [0,0,0,0]
goal = 0
counter = 0
print("Finding the solution please wait...")

while goal != 8:
    
    for i in range(0,4):
        values[i] = (checkFitness(board_dic[i]))

    # If goal found then display
    if(max(values) == 8):
        print("Solution Found...")
        print("Total Iterations: ", counter)
        print("Board: ")
        print(board_dic[values.index(max(values))])
        goal = 8

    # Getting the best 2 boards index
    best_2 = getBest2(values)

    # Getting the worst 2 boards index
    worst_2 = getWorst2(best_2)

    # Generating offsprings from the best 2

    # Performing Cross over
    list_dic[worst_2[0]] = getFirstOffSpring(list_dic, best_2)
    list_dic[worst_2[1]] = getSecondOffSpring(list_dic, best_2)
    
    # Performing mutation
    for i in range(0,2):
        mutate(list_dic[worst_2[i]])

    # Updating the boards with offsprings
    for i in range(0,2):
        board_dic[worst_2[i]] = updateBoard(list_dic, worst_2[i])
        board_dic[best_2[i]] = updateBoard(list_dic, best_2[i])
    counter +=1
    

Finding the solution please wait...
Solution Found...
Total Iterations:  0
Board: 
[[0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0.]]
